Repository workylab/materialize-angular, pull requests merged in 2019-07, with the labels that each got.

#30 Feature/drawer
  src/app/components/components.module.ts
  src/app/components/drawer-container/drawer-container.component.html
  src/app/components/drawer-container/drawer-container.component.ts
  src/app/components/drawer-content/drawer-content.component.html
  src/app/components/drawer-content/drawer-content.component.ts
  src/app/components/drawer-handler/drawer-handler.component.html
  src/app/components/drawer-handler/drawer-handler.component.ts
  src/app/components/drawer/drawer.component.html
  src/app/components/drawer/drawer.component.scss
  src/app/components/drawer/drawer.component.ts
  src/app/components/drawer/drawer.model.ts
  src/app/components/modal/modal.component.scss
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.scss
  src/app/components/navbar/navbar.component.ts
  src/app/components/navbar/navbar.model.ts
  src/app/directives/drawer-close.directive.ts
  src/app/modules/contacts/contacts.component.html
  src/app/modules/contacts/contacts.component.ts
Labels: feature

#31 Fixed files and added npm scripts.
  package.json
  src/app/app.component.ts
  src/app/components/button/button.model.ts
  src/app/components/calendar/calendar.component.ts
  src/app/components/collapsible/collapsible.component.ts
  src/app/components/components.module.ts
  src/app/components/div-tree/div-tree.component.ts
  src/app/components/drawer-container/drawer-container.component.ts
  src/app/components/drawer/drawer.component.ts
  src/app/components/drawer/drawer.model.ts
  src/app/components/dropdown/dropdown.model.ts
  src/app/components/icon/icon.component.ts
  src/app/components/input-file/input-file.component.ts
  src/app/components/input-file/input-file.model.ts
  src/app/components/modal/modal.component.scss
  src/app/components/modal/modal.component.ts
  src/app/components/radio-group/radio-group.component.ts
  src/app/components/select-option/select-option.component.ts
  src/app/components/select/select.component.ts
  src/app/components/sidenav/sidenav.component.html
  src/app/components/sidenav/sidenav.component.scss
  src/app/components/sidenav/sidenav.component.ts
  src/app/components/swiper/swiper.component.ts
  src/app/components/table/table.model.ts
  src/app/directives/ripple.directive.ts
  src/app/modules/home/home.component.ts
  src/app/utils/get-boolean-value.spec.ts
  src/index.html
  src/polyfills.ts
  src/public_api.ts
  src/tslint.json
  tslint.json
Labels: enhancement

#32 Added single run tests.
  .gitignore
  package.json
Labels: enhancement

#33 Feature/button toggle
  src/app/components/button-toggle-group/button-toggle-group.component.html
  src/app/components/button-toggle-group/button-toggle-group.component.scss
  src/app/components/button-toggle-group/button-toggle-group.component.ts
  src/app/components/button-toggle-group/button-toggle-group.model.ts
  src/app/components/button-toggle/button-toggle.component.html
  src/app/components/button-toggle/button-toggle.component.scss
  src/app/components/button-toggle/button-toggle.component.ts
  src/app/components/button-toggle/button-toggle.model.ts
  src/app/components/button/button.component.scss
  src/app/components/components.module.ts
  src/app/components/radio-group/radio-group.component.scss
  src/app/components/radio-group/radio-group.component.ts
  src/app/modules/contacts/contacts.component.html
  src/app/modules/contacts/contacts.component.ts
  src/app/modules/home/home.component.html
Labels: enhancement, feature

#34 Improved/range slider
  src/app/components/components.module.ts
  src/app/components/input-file/input-file.component.scss
  src/app/components/range-slider/range-slider.component.html
  src/app/components/range-slider/range-slider.component.scss
  src/app/components/range-slider/range-slider.component.ts
  src/app/components/range-slider/range-slider.model.ts
  src/app/components/select/select.component.ts
  src/app/components/slider-option/slider-option.component.html
  src/app/components/slider-option/slider-option.component.scss
  src/app/components/slider-option/slider-option.component.ts
  src/app/components/slider-option/slider-option.model.ts
  src/app/components/slider/slider.component.html
  src/app/components/slider/slider.component.scss
  src/app/components/slider/slider.component.ts
  src/app/components/slider/slider.model.ts
  src/app/modules/contacts/contacts.component.html
  src/app/modules/contacts/contacts.component.ts
  src/app/modules/home/home.component.html
  src/public_api.ts
Labels: enhancement, feature

#35 Hotfix/slider
  src/app/components/radio-group/radio-group.component.ts
  src/app/components/slider-option/slider-option.component.ts
  src/app/components/slider-option/slider-option.model.ts
  src/app/components/slider/slider.component.scss
  src/app/components/slider/slider.component.ts
  src/app/components/slider/slider.model.ts
  src/app/modules/contacts/contacts.component.html
  src/app/modules/contacts/contacts.component.ts
  src/app/modules/home/home.component.html
Labels: bug, enhancement

#37 Feature/list
  package-lock.json
  package.json
  src/app/components/components.module.ts
  src/app/components/drawer/drawer.component.html
  src/app/components/drawer/drawer.component.ts
  src/app/components/list-item/list-item.component.html
  src/app/components/list-item/list-item.component.scss
  src/app/components/list-item/list-item.component.ts
  src/app/components/list-item/list-item.model.ts
  src/app/components/list/list.component.html
  src/app/components/list/list.component.scss
  src/app/components/list/list.component.ts
  src/app/components/list/list.model.ts
  src/app/components/tab-group/tab-group.component.html
  src/app/components/tab-group/tab-group.component.scss
  src/app/components/tab-group/tab-group.component.ts
  src/app/modules/home/home.component.html
Labels: enhancement, feature

#39 Refactor/styles
  src/app/components/button/button.component.ts
  src/app/components/button/button.model.ts
  src/app/components/card/card.component.html
  src/app/components/card/card.component.ts
  src/app/components/card/card.model.ts
  src/app/components/components.module.ts
  src/app/components/dropdown/dropdown.component.html
  src/app/components/icon/icon.component.html
  src/app/components/icon/icon.component.scss
  src/app/components/icon/icon.component.ts
  src/app/components/icon/icon.model.ts
  src/app/components/label/label.component.html
  src/app/components/label/label.component.scss
  src/app/components/label/label.component.ts
  src/app/components/modal/modal.component.html
  src/app/components/radio-group/radio-group.component.html
  src/app/components/radio-group/radio-group.component.scss
  src/app/components/radio-group/radio-group.component.ts
  src/app/components/radio-group/radio-group.model.ts
  src/app/components/radio/radio.component.html
  src/app/components/radio/radio.component.scss
  src/app/components/radio/radio.component.ts
  src/app/components/slider-option/slider-option.component.ts
  src/app/components/slider/slider.component.ts
  src/app/components/table/table.component.html
  src/app/experimental/form-group/form-group.component.html
  src/app/experimental/form-group/form-group.component.scss
  src/app/experimental/form-group/form-group.component.ts
  src/app/modules/contacts/contacts.component.html
  src/app/modules/home/home.component.html
  src/public_api.ts
  src/styles/components/button.scss
  src/styles/components/card.scss
  src/styles/components/fonts.scss
  src/styles/components/icon.scss
  src/styles/components/label.scss
  src/styles/components/radio-group.scss
  src/styles/components/radio.scss
  src/styles/components/slider-option.scss
  src/styles/components/slider.scss
  src/styles/main.scss
  src/styles/theme/fonts.scss
  src/styles/theme/icons.scss
  src/styles/transitions/properties.scss
  src/styles/variables/buttons.scss
  src/styles/variables/cards.scss
  src/styles/variables/icons.scss
  src/styles/variables/labels.scss
  src/styles/variables/radios.scss
Labels: enhancement, feature

#40 Feature/utils tests
  package.json
  src/app/utils/clone-object.util.spec.ts
  src/app/utils/clone-object.util.ts
  src/app/utils/generate-uid.util.ts
  src/app/utils/get-boolean-value.spec.ts
  src/app/utils/get-boolean-value.util.spec.ts
Labels: enhancement

#41 Added color pallete.
  src/styles/main.scss
  src/styles/variables/colors.scss
Labels: enhancement

#44 Added button outline and text.
  src/app/completed-components/button/button.component.html
  src/app/completed-components/button/button.component.ts
  src/app/completed-components/button/button.model.ts
  src/app/modules/home/home.component.html
  src/styles/components/button.scss
  src/styles/variables/buttons.scss
Labels: enhancement

#43 Added typography styles.
  src/app/modules/home/home.component.html
  src/styles/css/typography.scss
  src/styles/main.scss
  src/styles/variables/typography.scss
Labels: enhancement

#46 Feature/css badges
  src/app/modules/home/home.component.html
  src/styles/css/badges.scss
  src/styles/main.scss
  src/styles/variables/badges.scss
Labels: enhancement

#47 Feature/css spinner loader
  src/app/modules/home/home.component.html
  src/styles/css/spinners.scss
  src/styles/main.scss
  src/styles/variables/spinners.scss
  src/styles/variables/typography.scss
Labels: enhancement

#48 Fixed linter.
  src/app/experimental/autocomplete/autocomplete.component.ts
  src/app/utils/clone-object.util.spec.ts
  src/app/utils/clone-object.util.ts
Labels: enhancement

#49 Improve/modal
  src/app/completed-components/form-message/form-message.component.html
  src/app/completed-components/form-message/form-message.component.ts
  src/app/completed-components/form-message/form-message.model.ts
  src/app/completed-components/modal-handler/modal-handler.component.html
  src/app/completed-components/modal-handler/modal-handler.component.ts
  src/app/completed-components/modal/modal.component.html
  src/app/completed-components/modal/modal.component.ts
  src/app/completed-components/modal/modal.model.ts
  src/app/components/components.module.ts
  src/app/components/form-message/form-message.component.html
  src/app/components/form-message/form-message.component.scss
  src/app/components/form-message/form-message.component.ts
  src/app/components/form-message/form-message.model.ts
  src/app/components/modal-content/modal-content.component.ts
  src/app/components/modal-handler/modal-handler.component.html
  src/app/components/modal-handler/modal-handler.component.ts
  src/app/components/modal/modal.component.html
  src/app/components/modal/modal.component.scss
  src/app/components/modal/modal.component.ts
  src/app/directives/modal-close.directive.ts
  src/app/modules/home/home.component.html
  src/public_api.ts
  src/styles/components/form-message.scss
  src/styles/components/modal.scss
  src/styles/main.scss
  src/styles/theme/colors.scss
  src/styles/variables/form-messages.scss
  src/styles/variables/modals.scss
Labels: enhancement, feature

#50 Hotfix/styles
  src/app/completed-components/button/button.component.html
  src/app/completed-components/button/button.component.ts
  src/app/completed-components/button/button.model.ts
  src/app/completed-components/radio-group/radio-group.component.html
  src/styles/components/modal.scss
  src/styles/components/ripple.scss
Labels: enhancement

#51 Feature/scroll spy
  LICENSE
  package.json
  src/app/completed-components/input/input.component.ts
  src/app/completed-components/navbar/navbar.component.ts
  src/app/completed-components/radio-group/radio-group.component.ts
  src/app/completed-components/scroll-spy-item/scroll-spy-item.component.html
  src/app/completed-components/scroll-spy-item/scroll-spy-item.component.ts
  src/app/completed-components/scroll-spy-item/scroll-spy-item.model.ts
  src/app/completed-components/scroll-spy/scroll-spy.component.html
  src/app/completed-components/scroll-spy/scroll-spy.component.ts
  src/app/completed-components/scroll-spy/scroll-spy.model.ts
  src/app/completed-components/select-option/select-option.component.ts
  src/app/completed-components/select/select.component.ts
  src/app/completed-components/slider-option/slider-option.component.ts
  src/app/completed-components/slider/slider.component.ts
  src/app/completed-components/step/step.component.ts
  src/app/completed-components/textarea/textarea.component.ts
  src/app/components/components.module.ts
  src/app/modules/home/home.component.html
  src/app/utils/window-scroll-position.util.ts
  src/package.json
Labels: feature

#52 Feature/glossary
  src/app/completed-components/glossary-item/glossary-item.component.html
  src/app/completed-components/glossary-item/glossary-item.component.ts
  src/app/completed-components/glossary-item/glossary-item.model.ts
  src/app/completed-components/glossary/glossary.component.component.ts
  src/app/completed-components/glossary/glossary.component.html
  src/app/completed-components/glossary/glossary.model.ts
  src/app/completed-components/scroll-spy/scroll-spy.component.ts
  src/app/components/components.module.ts
  src/app/modules/home/home.component.html
  src/styles/components/glossary-item.scss
  src/styles/main.scss
  src/styles/variables/glossary-items.scss
Labels: feature

#58 Feature/materliaze styles
  src/app/completed-components/glossary/glossary.component.component.ts
  src/app/completed-components/glossary/glossary.component.html
Labels: enhancement

#64 Update package.json
  package.json
Labels: enhancement

#63 Update package.json
  src/package.json
Labels: enhancement

#65 Feature/button toggle styles
  src/app/completed-components/button-toggle-group/button-toggle-group.component.html
  src/app/completed-components/button-toggle-group/button-toggle-group.component.ts
  src/app/completed-components/button-toggle-group/button-toggle-group.model.ts
  src/app/completed-components/button-toggle/button-toggle.component.html
  src/app/completed-components/button-toggle/button-toggle.component.ts
  src/app/completed-components/button-toggle/button-toggle.model.ts
  src/app/components/button-toggle-group/button-toggle-group.component.html
  src/app/components/button-toggle-group/button-toggle-group.component.scss
  src/app/components/button-toggle/button-toggle.component.scss
  src/app/components/button-toggle/button-toggle.component.ts
  src/app/components/components.module.ts
  src/app/modules/contacts/contacts.component.html
  src/public_api.ts
  src/styles/components/button-toggle-group.scss
  src/styles/components/button-toggle.scss
  src/styles/components/ripple.scss
  src/styles/main.scss
  src/styles/variables/button-toggle-group.scss
  src/styles/variables/button-toggle.scss
Labels: enhancement

#62 Added helps styles.
  src/app/modules/home/home.component.html
  src/styles/css/helpers.scss
  src/styles/main.scss
Labels: enhancement

#69 Add monthly downloads badge
  README.md
Labels: feature

#68 Fix/spam message
  package.json
  scripts/postinstall.js
  src/package.json
Labels: bug

#67 Fix/update dependencies
  .eslintrc
  package-lock.json
  package.json
  src/app/completed-components/modal/modal.component.ts
  src/app/completed-components/select-option/select-option.component.ts
  src/app/completed-components/select/select.component.ts
  src/app/completed-components/slider-option/slider-option.component.ts
  src/app/completed-components/slider/slider.component.ts
  src/app/completed-components/tab-group/tab-group.component.ts
  src/app/components/calendar/calendar.component.ts
  src/app/components/datepicker/datepicker.component.ts
  src/app/components/drawer/drawer.component.ts
  src/app/experimental/autocomplete/autocomplete.component.ts
  src/app/experimental/swiper-item/swiper-item.component.ts
  src/app/experimental/swiper/swiper.component.ts
  src/app/modules/contacts/contacts.component.ts
  src/package.json
  src/polyfills.ts
  src/styles/main.scss
  src/test.ts
  tsconfig.json
  webpack.config.js
Labels: bug

#71 Fixed tab styling.
  src/app/completed-components/tab-group/tab-group.component.ts
  src/styles/components/tab-group.scss
  src/styles/variables/tab-group.scss
Labels: enhancement

#73 Fixed variable names of tab group styles.
  src/styles/components/tab-group.scss
  src/styles/variables/tab-group.scss
Labels: enhancement
