Repository workylab/materialize-angular, pull requests merged in 2019-08, with the labels that each got.

#75 Refactor/collapsible
  src/app/completed-components/accordion/accordion.component.html
  src/app/completed-components/accordion/accordion.component.ts
  src/app/completed-components/accordion/accordion.model.ts
  src/app/completed-components/collapsible-content/collapsible-content.component.html
  src/app/completed-components/collapsible-content/collapsible-content.component.ts
  src/app/completed-components/collapsible-title/collapsible-title.component.html
  src/app/completed-components/collapsible-title/collapsible-title.component.ts
  src/app/completed-components/collapsible/collapsible.component.html
  src/app/completed-components/collapsible/collapsible.component.ts
  src/app/completed-components/collapsible/collapsible.model.ts
  src/app/components/accordion/accordion.component.html
  src/app/components/accordion/accordion.component.ts
  src/app/components/collapsible/collapsible.component.html
  src/app/components/collapsible/collapsible.component.scss
  src/app/components/collapsible/collapsible.component.ts
  src/app/components/components.module.ts
  src/app/modules/home/home.component.html
  src/public_api.ts
  src/styles/components/collapsible.scss
  src/styles/main.scss
  src/styles/transitions/properties.scss
  src/styles/variables/collapsible.scss
Labels: enhancement

#76 Added change label when slider indicator is moving.
  src/app/completed-components/slider/slider.component.ts
Labels: enhancement

#77 Fixed async on slider.
  src/app/completed-components/slider/slider.component.ts
Labels: bug

#83 Feature/stepper
  src/app/completed-components/step-indicator/step-indicator.component.html
  src/app/completed-components/step-indicator/step-indicator.component.ts
  src/app/completed-components/step-label/step-label.component.html
  src/app/completed-components/step-label/step-label.component.ts
  src/app/completed-components/step/step.component.html
  src/app/completed-components/step/step.component.ts
  src/app/completed-components/step/step.model.ts
  src/app/completed-components/stepper/stepper.component.html
  src/app/completed-components/stepper/stepper.component.ts
  src/app/completed-components/stepper/stepper.model.ts
  src/app/components/components.module.ts
  src/app/modules/contacts/contacts.component.html
  src/styles/components/stepper.scss
  src/styles/main.scss
  src/styles/variables/stepper.scss
Labels: feature

#84 Improved/stepper
  src/app/completed-components/stepper/stepper.component.html
  src/styles/components/stepper.scss
  src/styles/variables/stepper.scss
Labels: enhancement

#85 Feature/drawer
  src/app/completed-components/drawer-container/drawer-container.component.html
  src/app/completed-components/drawer-container/drawer-container.component.ts
  src/app/completed-components/drawer-content/drawer-content.component.html
  src/app/completed-components/drawer-content/drawer-content.component.ts
  src/app/completed-components/drawer/drawer.component.html
  src/app/completed-components/drawer/drawer.component.ts
  src/app/completed-components/drawer/drawer.model.ts
  src/app/components/components.module.ts
  src/app/components/drawer-handler/drawer-handler.component.html
  src/app/components/drawer-handler/drawer-handler.component.ts
  src/app/components/drawer/drawer.component.html
  src/app/components/drawer/drawer.component.scss
  src/app/components/drawer/drawer.component.ts
  src/app/modules/contacts/contacts.component.html
  src/public_api.ts
  src/styles/components/drawer.scss
  src/styles/main.scss
  src/styles/transitions/properties.scss
  src/styles/variables/drawer.scss
Labels: enhancement, feature

#86 Improved/switches
  src/styles/components/switch.scss
  src/styles/variables/switches.scss
Labels: enhancement

#88 Fix codeclimate badge link
  README.md
Labels: enhancement

#96 Fixed drawer component name.
  src/app/completed-components/drawer/drawer.module.ts
Labels: bug

#90 Feature/grid css
  src/app/modules/home/home.component.html
  src/styles/css/grid.scss
  src/styles/main.scss
  src/styles/variables/grid.scss
Labels: enhancement

#99 New release
  src/app/modules/home/home.component.html
  src/styles/css/grid.scss
  src/styles/main.scss
  src/styles/variables/grid.scss
Labels: feature

#100 Add code coverage in codeclimate.com
  .circleci/config.yml
Labels: enhancement

#103 Feature/lists
  src/app/completed-components/list-item/list-item.component.html
  src/app/completed-components/list-item/list-item.component.ts
  src/app/completed-components/list-item/list-item.model.ts
  src/app/completed-components/list/list.component.html
  src/app/completed-components/list/list.component.ts
  src/app/completed-components/list/list.model.ts
  src/app/components/list-item/list-item.component.ts
  src/app/components/list/list.component.scss
  src/styles/components/collapsible.scss
  src/styles/components/list.scss
  src/styles/variables/collapsible.scss
Labels: enhancement

#105 Improved browsers list.
  README.md
Labels: enhancement

#104 New Release
  README.md
  src/app/completed-components/list-item/list-item.component.html
  src/app/completed-components/list-item/list-item.component.ts
  src/app/completed-components/list-item/list-item.model.ts
  src/app/completed-components/list/list.component.html
  src/app/completed-components/list/list.component.ts
  src/app/completed-components/list/list.model.ts
  src/app/components/list-item/list-item.component.ts
  src/app/components/list/list.component.scss
  src/styles/components/collapsible.scss
  src/styles/components/list.scss
  src/styles/variables/collapsible.scss
Labels: enhancement

#107 New Release
  src/styles/components/collapsible.scss
  src/styles/variables/collapsible.scss
Labels: enhancement

#108 Feature/tests/accordion
  src/app/completed-components/accordion/accordion.component.spec.ts
  src/app/completed-components/accordion/accordion.component.ts
  src/app/completed-components/accordion/accordion.model.ts
  src/app/completed-components/button/button.component.spec.ts
  src/styles/components/tab-group.scss
  src/styles/variables/tab-group.scss
Labels: enhancement, feature

#109 New Release
  README.md
  src/app/completed-components/accordion/accordion.component.spec.ts
  src/app/completed-components/accordion/accordion.component.ts
  src/app/completed-components/accordion/accordion.model.ts
  src/app/completed-components/button/button.component.spec.ts
  src/styles/components/tab-group.scss
  src/styles/variables/tab-group.scss
Labels: enhancement, feature

#112 Add why materialize angular readme content
  README.md
Labels: enhancement

#111 Features readme
  README.md
Labels: enhancement

#113 Feature/modules export
  src/app/completed-components/input/input.module.ts
  src/public_api.ts
Labels: enhancement

#114 New Release
  README.md
  package-lock.json
  package.json
  scss-bundle.config.json
  src/app/completed-components/button/button.component.spec.ts
  src/app/completed-components/input/input.module.ts
  src/public_api.ts
Labels: enhancement

#121 Fix/event names
  package-lock.json
  package.json
  src/app/completed-components/collapsible/collapsible.component.ts
  src/app/completed-components/glossary/glossary-item/glossary-item.component.ts
  src/app/completed-components/input/input.component.ts
  src/app/completed-components/scroll-spy/scroll-spy.component.ts
  src/app/modules/contacts/contacts.component.html
  src/app/modules/home/home.component.html
  src/package.json
Labels: enhancement

#122 New release
  npm_publish.sh
  package-lock.json
  package.json
  src/app/completed-components/collapsible/collapsible.component.ts
  src/app/completed-components/glossary/glossary-item/glossary-item.component.ts
  src/app/completed-components/input/input.component.ts
  src/app/completed-components/scroll-spy/scroll-spy.component.ts
  src/app/modules/contacts/contacts.component.html
  src/app/modules/home/home.component.html
  src/package.json
  src/styles/css/grid.scss
  update_packages.sh
Labels: enhancement

#125 Merge back
  CHANGELOG.md
  package-lock.json
  package.json
  src/package.json
Labels: nochangelog

#128 Removed background-color properties
  src/styles/components/button-toggle-group.scss
  src/styles/components/button-toggle.scss
  src/styles/components/card.scss
  src/styles/components/date-picker.scss
  src/styles/components/drawer.scss
  src/styles/components/html-visualizer.scss
  src/styles/components/list.scss
  src/styles/components/radio-group.scss
  src/styles/components/ripple.scss
  src/styles/components/select-option.scss
  src/styles/components/select.scss
  src/styles/components/slider.scss
  src/styles/css/badges.scss
  src/styles/css/spinners.scss
  src/styles/placeholders/forms.scss
  src/styles/variables/badges.scss
  src/styles/variables/cards.scss
Labels: enhancement
