Repository workylab/materialize-angular, pull requests merged in 2019-09, with the labels that each got.

#126 Fixed border radius on float label.
  src/styles/components/form.scss
Labels: bug

#127 Removed space-none unnecessary variable.
  src/styles/theme/metrics.scss
  src/styles/variables/button-toggle-group.scss
  src/styles/variables/cards.scss
  src/styles/variables/checkboxes.scss
  src/styles/variables/collapsible.scss
  src/styles/variables/form-messages.scss
  src/styles/variables/forms.scss
  src/styles/variables/labels.scss
  src/styles/variables/navbars.scss
  src/styles/variables/radios.scss
  src/styles/variables/slider-options.scss
  src/styles/variables/sliders.scss
  src/styles/variables/stepper.scss
  src/styles/variables/switches.scss
Labels: enhancement

#130 Feature/space helpers
  src/app/modules/home/home.component.html
  src/styles/css/helpers.scss
  src/styles/css/spacing.scss
  src/styles/main.scss
  src/styles/variables/spacing.scss
Labels: enhancement

#129 New release
  src/app/modules/home/home.component.html
  src/styles/components/button-toggle-group.scss
  src/styles/components/button-toggle.scss
  src/styles/components/card.scss
  src/styles/components/date-picker.scss
  src/styles/components/drawer.scss
  src/styles/components/form.scss
  src/styles/components/html-visualizer.scss
  src/styles/components/list.scss
  src/styles/components/radio-group.scss
  src/styles/components/ripple.scss
  src/styles/components/select-option.scss
  src/styles/components/select.scss
  src/styles/components/slider.scss
  src/styles/css/badges.scss
  src/styles/css/helpers.scss
  src/styles/css/spacing.scss
  src/styles/css/spinners.scss
  src/styles/main.scss
  src/styles/placeholders/forms.scss
  src/styles/theme/metrics.scss
  src/styles/variables/badges.scss
  src/styles/variables/button-toggle-group.scss
  src/styles/variables/cards.scss
  src/styles/variables/checkboxes.scss
  src/styles/variables/collapsible.scss
  src/styles/variables/form-messages.scss
  src/styles/variables/forms.scss
  src/styles/variables/labels.scss
  src/styles/variables/navbars.scss
  src/styles/variables/radios.scss
  src/styles/variables/slider-options.scss
  src/styles/variables/sliders.scss
  src/styles/variables/spacing.scss
  src/styles/variables/stepper.scss
  src/styles/variables/switches.scss
Labels: enhancement

#135 Add merge back when npm publish
  npm_publish.sh
Labels: enhancement

#136 Change logo url to CDN
  README.md
Labels: enhancement

#134 Feature/datepicker
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/completed-components/button/button.component.ts
  src/app/completed-components/calendar/calendar.component.html
  src/app/completed-components/calendar/calendar.component.ts
  src/app/completed-components/calendar/calendar.model.ts
  src/app/completed-components/calendar/calendar.module.ts
  src/app/completed-components/datepicker/datepicker.component.html
  src/app/completed-components/datepicker/datepicker.component.ts
  src/app/completed-components/datepicker/datepicker.model.ts
  src/app/completed-components/datepicker/datepicker.module.ts
  src/app/components/calendar/calendar.component.scss
  src/app/components/datepicker/datepicker.component.html
  src/app/fixtures/calendar-months.ts
  src/app/fixtures/calendar-week-days.ts
  src/app/modules/home/home.component.html
  src/package.json
  src/public_api.ts
  src/styles/components/calendar.scss
  src/styles/components/date-picker.scss
  src/styles/main.scss
  src/styles/theme/fonts.scss
  src/styles/variables/calendar.scss
  src/styles/variables/date-picker.scss
  src/styles/variables/forms.scss
  src/styles/variables/labels.scss
  src/styles/variables/main.scss
Labels: enhancement

#131 Hotfix/grid padding
  .stylelintrc
  src/styles/css/grid.scss
Labels: bug

#137 New release
  .stylelintrc
  README.md
  npm_publish.sh
  src/app/app.module.ts
  src/app/completed-components/button/button.component.ts
  src/app/completed-components/calendar/calendar.component.html
  src/app/completed-components/calendar/calendar.component.ts
  src/app/completed-components/calendar/calendar.model.ts
  src/app/completed-components/calendar/calendar.module.ts
  src/app/completed-components/datepicker/datepicker.component.html
  src/app/completed-components/datepicker/datepicker.component.ts
  src/app/completed-components/datepicker/datepicker.model.ts
  src/app/completed-components/datepicker/datepicker.module.ts
  src/app/components/calendar/calendar.component.scss
  src/app/components/datepicker/datepicker.component.html
  src/app/fixtures/calendar-months.ts
  src/app/fixtures/calendar-week-days.ts
  src/app/modules/home/home.component.html
  src/public_api.ts
  src/styles/components/calendar.scss
  src/styles/components/date-picker.scss
  src/styles/css/grid.scss
  src/styles/main.scss
  src/styles/theme/fonts.scss
  src/styles/variables/calendar.scss
  src/styles/variables/date-picker.scss
  src/styles/variables/forms.scss
  src/styles/variables/labels.scss
  src/styles/variables/main.scss
Labels: nochangelog

#139 Improved/date picker
  src/app/completed-components/calendar/calendar.component.ts
  src/app/completed-components/datepicker/datepicker.component.html
  src/app/completed-components/datepicker/datepicker.component.ts
  src/app/completed-components/datepicker/datepicker.model.ts
  src/app/modules/contacts/contacts.component.html
  src/app/modules/contacts/contacts.component.ts
Labels: enhancement

#140 New release
  src/app/completed-components/calendar/calendar.component.ts
  src/app/completed-components/datepicker/datepicker.component.html
  src/app/completed-components/datepicker/datepicker.component.ts
  src/app/completed-components/datepicker/datepicker.model.ts
  src/app/modules/contacts/contacts.component.html
  src/app/modules/contacts/contacts.component.ts
Labels: enhancement

#141 Feature/styling/calendar button
  src/styles/components/calendar.scss
  src/styles/variables/calendar.scss
Labels: enhancement

#142 New release
  src/styles/components/calendar.scss
  src/styles/variables/calendar.scss
Labels: nochangelog

#143 Fixed padding grid.
  src/styles/css/grid.scss
Labels: bug

#145 Fix bug in build package script
  package.json
Labels: bug

#146 Hotfix/tab events
  src/app/completed-components/tab-group/tab-group.component.ts
Labels: enhancement

#147 New release
  README.md
  package.json
  src/app/completed-components/tab-group/tab-group.component.ts
  src/styles/css/grid.scss
Labels: nochangelog

#155 Fix typo in styles
  src/styles/modules/common/form.styles.scss
  src/styles/modules/common/form.variables.scss
Labels: bug

#157 Fix calendar break on null value
  src/app/completed-components/calendar/calendar.component.html
  src/app/completed-components/calendar/calendar.component.ts
  src/app/completed-components/calendar/calendar.model.ts
  src/app/modules/home/home.component.html
Labels: bug

#154 Added gray scale values.
  src/app/components/dropdown/dropdown.component.scss
  src/app/components/table/table.component.scss
  src/app/components/tooltip/tooltip.component.scss
  src/app/experimental/autocomplete/autocomplete.component.scss
  src/app/experimental/form-group/form-group.component.scss
  src/styles/components/list.scss
  src/styles/modules/button-toggle-group/button-toggle-group.variables.scss
  src/styles/modules/button-toggle-group/button-toggle.variables.scss
  src/styles/modules/button/button.variables.scss
  src/styles/modules/calendar/calendar.variables.scss
  src/styles/modules/card/card.variables.scss
  src/styles/modules/checkbox/checkbox.variables.scss
  src/styles/modules/collapsible/collapsible.variables.scss
  src/styles/modules/common/form.variables.scss
  src/styles/modules/date-picker/date-picker.variables.scss
  src/styles/modules/form-message/form-message.variables.scss
  src/styles/modules/glossary/glossary-item.variables.scss
  src/styles/modules/icon/icon.variables.scss
  src/styles/modules/modal/modal.variables.scss
  src/styles/modules/radio-group/radio.variables.scss
  src/styles/modules/select/select-option.variables.scss
  src/styles/modules/select/select.styles.scss
  src/styles/modules/slider/slider-option.variables.scss
  src/styles/modules/slider/slider.variables.scss
  src/styles/modules/stepper/stepper.variables.scss
  src/styles/modules/switch/switch.variables.scss
  src/styles/modules/tab-group/tab-group.variables.scss
  src/styles/theme/colors.scss
Labels: enhancement

#159 Hotfix/css modules
  src/styles/config.scss
  src/styles/main.scss
  src/styles/modules/button-toggle-group/main.scss
  src/styles/modules/button/main.scss
  src/styles/modules/calendar/main.scss
  src/styles/modules/card/main.scss
  src/styles/modules/checkbox/main.scss
  src/styles/modules/collapsible/main.scss
  src/styles/modules/common/main.scss
  src/styles/modules/date-picker/main.scss
  src/styles/modules/drawer/main.scss
  src/styles/modules/font/main.scss
  src/styles/modules/form-message/main.scss
  src/styles/modules/glossary/main.scss
  src/styles/modules/icon/main.scss
  src/styles/modules/input/main.scss
  src/styles/modules/label/main.scss
  src/styles/modules/modal/main.scss
  src/styles/modules/navbar/main.scss
  src/styles/modules/radio-group/main.scss
  src/styles/modules/select/main.scss
  src/styles/modules/slider/main.scss
  src/styles/modules/stepper/main.scss
  src/styles/modules/switch/main.scss
  src/styles/modules/tab-group/main.scss
  src/styles/modules/textarea/main.scss
Labels: bug

#161 Fixed tab header animation when component is loaded.
  src/app/completed-components/tab-group/tab-group.component.ts
Labels: bug

#160 New release
  src/app/completed-components/tab-group/tab-group.component.ts
  src/app/components/dropdown/dropdown.component.scss
  src/app/components/table/table.component.scss
  src/app/components/tooltip/tooltip.component.scss
  src/app/experimental/autocomplete/autocomplete.component.scss
  src/app/experimental/form-group/form-group.component.scss
  src/styles/components/list.scss
  src/styles/config.scss
  src/styles/main.scss
  src/styles/modules/button-toggle-group/button-toggle-group.variables.scss
  src/styles/modules/button-toggle-group/button-toggle.variables.scss
  src/styles/modules/button-toggle-group/main.scss
  src/styles/modules/button/button.variables.scss
  src/styles/modules/button/main.scss
  src/styles/modules/calendar/calendar.variables.scss
  src/styles/modules/calendar/main.scss
  src/styles/modules/card/card.variables.scss
  src/styles/modules/card/main.scss
  src/styles/modules/checkbox/checkbox.variables.scss
  src/styles/modules/checkbox/main.scss
  src/styles/modules/collapsible/collapsible.variables.scss
  src/styles/modules/collapsible/main.scss
  src/styles/modules/common/form.variables.scss
  src/styles/modules/common/main.scss
  src/styles/modules/date-picker/date-picker.variables.scss
  src/styles/modules/date-picker/main.scss
  src/styles/modules/drawer/main.scss
  src/styles/modules/font/main.scss
  src/styles/modules/form-message/form-message.variables.scss
  src/styles/modules/form-message/main.scss
  src/styles/modules/glossary/glossary-item.variables.scss
  src/styles/modules/glossary/main.scss
  src/styles/modules/icon/icon.variables.scss
  src/styles/modules/icon/main.scss
  src/styles/modules/input/main.scss
  src/styles/modules/label/main.scss
  src/styles/modules/modal/main.scss
  src/styles/modules/modal/modal.variables.scss
  src/styles/modules/navbar/main.scss
  src/styles/modules/radio-group/main.scss
  src/styles/modules/radio-group/radio.variables.scss
  src/styles/modules/select/main.scss
  src/styles/modules/select/select-option.variables.scss
  src/styles/modules/select/select.styles.scss
  src/styles/modules/slider/main.scss
  src/styles/modules/slider/slider-option.variables.scss
  src/styles/modules/slider/slider.variables.scss
  src/styles/modules/stepper/main.scss
  src/styles/modules/stepper/stepper.variables.scss
  src/styles/modules/switch/main.scss
  src/styles/modules/switch/switch.variables.scss
  src/styles/modules/tab-group/main.scss
  src/styles/modules/tab-group/tab-group.variables.scss
  src/styles/modules/textarea/main.scss
  src/styles/theme/colors.scss
Labels: nochangelog

#162 Fix/glossary scroll
  src/app/completed-components/glossary/glossary.component.ts
  src/app/completed-components/glossary/glossary.model.ts
  src/app/completed-components/scroll-spy/scroll-spy-item/scroll-spy-item.component.ts
  src/app/completed-components/scroll-spy/scroll-spy.component.ts
  src/app/modules/home/home.component.html
  src/app/utils/get-offset-top.util.ts
Labels: enhancement

#163 New release
  src/app/completed-components/glossary/glossary.component.ts
  src/app/completed-components/glossary/glossary.model.ts
  src/app/completed-components/scroll-spy/scroll-spy-item/scroll-spy-item.component.ts
  src/app/completed-components/scroll-spy/scroll-spy.component.ts
  src/app/modules/home/home.component.html
  src/app/utils/get-offset-top.util.ts
Labels: nochangelog

#164 Fixed calc to validate scroll top.
  src/app/completed-components/glossary/glossary.component.ts
Labels: bug

#165 New release
  src/app/completed-components/glossary/glossary.component.ts
Labels: nochangelog

#166 Added default parameter to button toggle variables.
  src/styles/modules/button-toggle-group/button-toggle.variables.scss
Labels: bug

#167 Add (change) nochangelog label to release
  npm_publish.sh
Labels: enhancement

#168 Add patreon badge and raising funds documentation
  README.md
Labels: enhancement

#170 Added ripple styles.
  src/app/completed-components/common/ripple.directive.ts
  src/app/modules/home/home.component.html
  src/styles/components/ripple.scss
  src/styles/main.scss
  src/styles/modules/ripple/main.scss
  src/styles/modules/ripple/ripple.styles.scss
  src/styles/modules/ripple/ripple.variables.scss
  src/styles/theme/transitions.scss
Labels: enhancement

#169 Removed duplicated variable and added default property.
  src/styles/modules/checkbox/checkbox.variables.scss
Labels: bug, enhancement

#171 New release
  README.md
  npm_publish.sh
  src/app/completed-components/common/ripple.directive.ts
  src/app/modules/home/home.component.html
  src/styles/components/ripple.scss
  src/styles/main.scss
  src/styles/modules/button-toggle-group/button-toggle.variables.scss
  src/styles/modules/checkbox/checkbox.variables.scss
  src/styles/modules/ripple/main.scss
  src/styles/modules/ripple/ripple.styles.scss
  src/styles/modules/ripple/ripple.variables.scss
  src/styles/theme/transitions.scss
Labels: release

#172 Add stop on warning during linting
  package.json
Labels: priority: low, status: completed, type: enhancement, work: obvious

#173 Feature/button native element
  src/app/completed-components/button/button.component.html
  src/app/completed-components/button/button.component.ts
Labels: status: accepted, type: enhancement

#174 New release
  package.json
  src/app/completed-components/button/button.component.html
  src/app/completed-components/button/button.component.ts
Labels: release

#177 Add labels description
  CONTRIBUTING.md
Labels: priority: low, status: completed, type: enhancement, work: obvious

#178 Fixed styles and selectors.
  src/styles/modules/drawer/drawer.styles.scss
Labels: type: bug

#180 Check features and fix urls
  README.md
Labels: priority: low, status: accepted, type: enhancement, work: obvious

#175 Added null default value in id attributes
  src/app/completed-components/checkbox/checkbox.component.html
  src/app/completed-components/checkbox/checkbox.component.ts
  src/app/completed-components/checkbox/checkbox.model.ts
  src/app/completed-components/radio-group/radio-group.component.ts
  src/app/completed-components/radio-group/radio-group.model.ts
  src/app/completed-components/radio-group/radio/radio.component.ts
  src/app/completed-components/radio-group/radio/radio.model.ts
  src/app/completed-components/switch/switch.component.html
  src/app/completed-components/switch/switch.component.ts
  src/app/completed-components/switch/switch.model.ts
  src/app/completed-components/textarea/textarea.component.html
  src/app/completed-components/textarea/textarea.component.ts
  src/app/completed-components/textarea/textarea.model.ts
  src/styles/modules/switch/switch.styles.scss
  src/styles/modules/switch/switch.variables.scss
Labels: type: enhancement

#182 New release
  README.md
  src/app/completed-components/checkbox/checkbox.component.html
  src/app/completed-components/checkbox/checkbox.component.ts
  src/app/completed-components/checkbox/checkbox.model.ts
  src/app/completed-components/radio-group/radio-group.component.ts
  src/app/completed-components/radio-group/radio-group.model.ts
  src/app/completed-components/radio-group/radio/radio.component.ts
  src/app/completed-components/radio-group/radio/radio.model.ts
  src/app/completed-components/slider/slider.component.html
  src/app/completed-components/slider/slider.component.ts
  src/app/completed-components/switch/switch.component.html
  src/app/completed-components/switch/switch.component.ts
  src/app/completed-components/switch/switch.model.ts
  src/app/completed-components/textarea/textarea.component.html
  src/app/completed-components/textarea/textarea.component.ts
  src/app/completed-components/textarea/textarea.model.ts
  src/styles/modules/slider/slider.styles.scss
  src/styles/modules/slider/slider.variables.scss
  src/styles/modules/switch/switch.styles.scss
  src/styles/modules/switch/switch.variables.scss
Labels: release
